///////////////////////////////////////////////////////////////////////////////
//
// Revolution external definition file for 'cTest'
//
// Generated by External Creator V1.00
//
// For language:
//

#include <revolution/external.h>

#include <stdio.h>
#include <stdlib.h>

///////////////////////////////////////////////////////////////////////////////
//
// BEGIN USER DEFINITIONS
void cTest(char *args[], int nargs, char **retstring, Bool *pass, Bool *error){
  char ch;
  char intro[] = "Testing C Code ... Listing ASCII Values 75 to 100";
  printf("%s\n", intro);
  /*for( ch = 75; ch <= 100; ch++){
    printf("ASCII value = %d, Character = %c\n", ch, ch);
  }
  */
}
// END USER DEFINITIONS
//
///////////////////////////////////////////////////////////////////////////////


EXTERNAL_BEGIN_DECLARATIONS("cTest")

// BEGIN USER DECLARATIONS
EXTERNAL_DECLARE_COMMAND("cTest", cTest)
// END USER DECLARATIONS

EXTERNAL_END_DECLARATIONS
