NAME=ctest
TYPE=library

SOURCES=ctest.c

# To add your own source files put them into this list.
# Note that source files are searched for in src/
#
CUSTOM_DEFINES=

# Add any custom include directions needed by your
# external to this list
#
CUSTOM_INCLUDES=./src

# Add any custom static libraries needed by your external
# to this list
#
CUSTOM_STATIC_LIBS=external

# Add any custom dynamic libraries needed by your external
# to this list
#
CUSTOM_DYNAMIC_LIBS=

# Add any specific compiler options you need here
#
CUSTOM_CCFLAGS=
#-fno-exceptions -fno-rtti

# Add any specific link options you need here
#
CUSTOM_LDFLAGS=

include ../configurations/library.linux.makefile
